-- ComplytEX / Safety-Final schema for Supabase (PostgreSQL)
-- Generated for migration from SQL Server

create extension if not exists pgcrypto;

-- =========================
-- Core RBAC + tenant schema
-- =========================

create table if not exists business_types (
  business_type_id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists tenants (
  tenant_id integer generated by default as identity primary key,
  name text not null unique,
  business_type_id integer not null references business_types(business_type_id),
  external_id uuid not null default gen_random_uuid(),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists users (
  user_id integer generated by default as identity primary key,
  email text not null unique,
  full_name text null,
  password_hash bytea not null,
  password_salt bytea not null,
  is_active boolean not null default true,
  email_verified boolean not null default false,
  two_fa_enabled boolean not null default false,
  two_fa_secret bytea null,
  cell_phone text null,
  designation text null,
  avatar_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists email_verifications (
  token_id uuid primary key default gen_random_uuid(),
  user_id integer not null references users(user_id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists visitor_logs (
  log_id bigint generated by default as identity primary key,
  tenant_id integer null,
  user_id integer null,
  path text not null,
  method text not null,
  ip text null,
  user_agent text null,
  referrer text null,
  country text null,
  region text null,
  city text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_visitor_logs_tenant_time on visitor_logs(tenant_id, created_at desc);

create table if not exists subscriptions (
  subscription_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  stripe_customer_id text null,
  stripe_subscription_id text null,
  status text not null default 'inactive',
  plan_name text null,
  credit_balance integer not null default 0,
  current_period_end timestamptz null,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  invoice_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  stripe_invoice_id text null,
  amount_cents integer not null,
  currency text not null default 'usd',
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists credit_top_ups (
  top_up_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  stripe_session_id text null,
  stripe_payment_intent text null,
  credits integer not null,
  amount_cents integer not null,
  currency text not null default 'usd',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);
create index if not exists ix_credit_top_ups_tenant on credit_top_ups(tenant_id, created_at desc);

create table if not exists credit_usage (
  usage_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  user_id integer null references users(user_id),
  credits integer not null,
  reason text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_credit_usage_tenant on credit_usage(tenant_id, created_at desc);

create table if not exists tickets (
  ticket_id integer generated by default as identity primary key,
  tenant_id integer null,
  created_by integer null references users(user_id),
  subject text not null,
  status text not null default 'open',
  priority text not null default 'normal',
  created_at timestamptz not null default now()
);

create table if not exists ticket_messages (
  message_id integer generated by default as identity primary key,
  ticket_id integer not null references tickets(ticket_id) on delete cascade,
  user_id integer null references users(user_id),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists company_users (
  company_user_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  user_id integer not null references users(user_id) on delete cascade,
  title text null,
  is_owner boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, user_id)
);

create table if not exists modules (
  module_id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists permissions (
  permission_id integer generated by default as identity primary key,
  code text not null unique,
  description text null,
  module_id integer null references modules(module_id)
);

create table if not exists roles (
  role_id integer generated by default as identity primary key,
  tenant_id integer null references tenants(tenant_id) on delete cascade,
  name text not null,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);

create table if not exists role_permissions (
  role_id integer not null references roles(role_id) on delete cascade,
  permission_id integer not null references permissions(permission_id) on delete cascade,
  primary key (role_id, permission_id)
);

create table if not exists user_roles (
  tenant_id integer not null references tenants(tenant_id),
  user_id integer not null references users(user_id) on delete cascade,
  role_id integer not null references roles(role_id) on delete cascade,
  primary key (tenant_id, user_id, role_id)
);

create table if not exists audit_logs (
  audit_id bigint generated by default as identity primary key,
  tenant_id integer null,
  user_id integer null,
  action text not null,
  entity text null,
  entity_id text null,
  details text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_audit_logs_tenant_time on audit_logs(tenant_id, created_at desc);

create table if not exists customers (
  customer_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  name text not null,
  email text null,
  phone text null,
  created_at timestamptz not null default now()
);

create table if not exists suppliers (
  supplier_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  name text not null,
  email text null,
  phone text null,
  created_at timestamptz not null default now()
);

create table if not exists certifications (
  certification_id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(tenant_id) on delete cascade,
  name text not null,
  issuer text null,
  issue_date date null,
  expiry_date date null,
  created_at timestamptz not null default now()
);

-- =========================
-- Auth support tables
-- =========================

create table if not exists user_two_factor (
  user_id integer primary key references users(user_id) on delete cascade,
  secret text not null,
  enabled boolean not null default false,
  created_at timestamptz not null default now(),
  last_used_at timestamptz null
);

create table if not exists login_otps (
  id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade,
  code text not null,
  expires_at timestamptz not null,
  consumed boolean not null default false,
  created_at timestamptz not null default now()
);

-- =========================
-- Accounting + company profile
-- =========================

create table if not exists chart_of_accounts (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  account_type text not null,
  account_name text not null,
  account_number text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_chart_of_accounts_tenant on chart_of_accounts(tenant_id, account_type, account_name);

create table if not exists company_profile (
  tenant_id integer primary key,
  address1 text null,
  address2 text null,
  city text null,
  state text null,
  postal_code text null,
  country text null,
  employees integer null,
  capacity_type text null,
  capacity_qty integer null,
  min_order_qty integer null,
  sales_profit_type text null,
  sales_profit_value numeric(18,2) null,
  min_wage numeric(18,2) null,
  min_age integer null,
  retirement_age integer null,
  deal_in_garments boolean not null default false,
  deal_in_home_textile boolean not null default false,
  logo_url text null,
  updated_at timestamptz not null default now()
);

create table if not exists company_product_line (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists company_warehouse (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  address_type text null,
  warehouse_type text null,
  address1 text null,
  address2 text null,
  city text null,
  state text null,
  postal_code text null,
  country text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists company_space (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  type text null,
  purpose text null,
  floor integer null,
  width numeric(18,2) null,
  length numeric(18,2) null,
  height numeric(18,2) null,
  unit text null,
  capacity text null,
  ventilation text null,
  doors integer null,
  windows integer null,
  exit_plan_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists company_assets (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  asset_name text not null,
  asset_type text null,
  quantity integer null,
  purchase_date date null,
  purchase_price numeric(18,2) null,
  supplier text null,
  notes text null,
  saved_on date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists company_certification (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  type text null,
  policy text null,
  name text not null,
  valid_from date null,
  valid_till date null,
  detail text null,
  cert_image_url text null,
  logo_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists company_union (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  description text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

create table if not exists banks (
  bank_id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  account_title text null,
  account_number text null,
  branch_name text null,
  notes text null,
  opening_balance numeric(18,2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists ix_banks_tenant on banks(tenant_id);

create table if not exists bank_ledger (
  ledger_id bigint generated by default as identity primary key,
  tenant_id integer not null,
  bank_id integer not null,
  entry_type char(2) not null,
  amount numeric(18,2) not null,
  quantity integer null,
  reference text null,
  party text null,
  slip_number text null,
  doc_url text null,
  entry_date timestamptz not null default now(),
  created_by integer null
);
create index if not exists ix_ledger_tenant_bank on bank_ledger(tenant_id, bank_id, entry_date);

create table if not exists ap_invoices (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  order_id text null,
  product_name text null,
  due_date date null,
  supplier_name text null,
  amount numeric(18,2) not null,
  status text not null default 'Pending',
  doc_url text null,
  notes text null,
  bank_id integer null,
  created_by integer null,
  created_at timestamptz not null default now(),
  approved_by integer null,
  approved_at timestamptz null,
  paid_by integer null,
  paid_at timestamptz null
);
create index if not exists ix_ap_tenant_status on ap_invoices(tenant_id, status);

create table if not exists ar_invoices (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  order_id text null,
  product_name text null,
  due_date date null,
  customer_name text null,
  amount numeric(18,2) not null,
  status text not null default 'Pending',
  doc_url text null,
  notes text null,
  bank_id integer null,
  created_by integer null,
  created_at timestamptz not null default now(),
  received_by integer null,
  received_at timestamptz null
);
create index if not exists ix_ar_tenant_status on ar_invoices(tenant_id, status);

-- =========================
-- HR tables
-- =========================

create table if not exists job_posting (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  title text not null,
  department text null,
  type text null,
  openings integer not null default 1,
  location text null,
  salary_range text null,
  description text null,
  required_qualification text null,
  desired_qualification text null,
  application_deadline date null,
  diversity_flag boolean not null default false,
  eoe_flag boolean not null default false,
  posted_at timestamptz not null default now()
);
create index if not exists ix_job_posting_tenant on job_posting(tenant_id, posted_at desc);

create table if not exists candidate (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  job_posting_id integer null,
  name text not null,
  email text not null,
  phone text null,
  address text null,
  linkedin_url text null,
  work_auth_status text null,
  preferred_start_date date null,
  status text not null default 'Applied',
  applied_at timestamptz not null default now(),
  shortlisted boolean not null default false,
  shortlisted_at timestamptz null
);
create index if not exists ix_candidate_tenant on candidate(tenant_id, applied_at desc);

create table if not exists candidate_interview (
  id integer generated by default as identity primary key,
  candidate_id integer not null,
  tenant_id integer not null,
  interview_date date null,
  interview_time_slot text null,
  interview_type text null,
  interviewer_name text null,
  interviewer_title text null,
  reason text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_candidate_interview_tenant on candidate_interview(tenant_id, candidate_id);

create table if not exists candidate_evaluation (
  id integer generated by default as identity primary key,
  candidate_id integer not null,
  tenant_id integer not null,
  evaluator_name text null,
  technical_skills text null,
  teamwork text null,
  leadership text null,
  problem_solving text null,
  communication text null,
  test_details text null,
  agenda text null,
  recommendation text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_candidate_evaluation_tenant on candidate_evaluation(tenant_id, candidate_id);

create table if not exists candidate_offer (
  id integer generated by default as identity primary key,
  candidate_id integer not null,
  tenant_id integer not null,
  employment_type text null,
  benefits text null,
  salary_offer text null,
  start_date date null,
  confidentiality boolean not null default false,
  non_compete boolean not null default false,
  at_will boolean not null default false,
  offer_status text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_candidate_offer_tenant on candidate_offer(tenant_id, candidate_id);

create table if not exists hr_employee_profile (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  employee_id integer not null,
  address1 text null,
  address2 text null,
  active boolean not null default true,
  phone text null,
  country text null,
  state text null,
  zip text null,
  fax text null,
  department text null,
  employee_type text null,
  ssn text null,
  email text null,
  hire_date date null,
  birth_date date null,
  commissionable boolean not null default false,
  commission_percent numeric(5,2) null,
  next_of_kin_name text null,
  next_of_kin_number text null,
  source_type text null,
  industry text null,
  geo_location text null,
  disability text null,
  work_injury text null,
  health_insurance text null,
  id_number text null,
  notes text null,
  heritage text null,
  sexual_orientation text null,
  job_description text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_hr_employee_profile_tenant on hr_employee_profile(tenant_id, employee_id);

create table if not exists hr_employee_totals (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  employee_id integer not null,
  mtd_gross numeric(18,2) null,
  mtd_state numeric(18,2) null,
  qtd_gross numeric(18,2) null,
  qtd_state numeric(18,2) null,
  ytd_gross numeric(18,2) null,
  ytd_state numeric(18,2) null,
  mtd_fica numeric(18,2) null,
  qtd_fica numeric(18,2) null,
  ytd_fica numeric(18,2) null,
  mtd_local numeric(18,2) null,
  qtd_local numeric(18,2) null,
  ytd_local numeric(18,2) null,
  mtd_federal numeric(18,2) null,
  qtd_federal numeric(18,2) null,
  ytd_federal numeric(18,2) null,
  mtd_other numeric(18,2) null,
  qtd_other numeric(18,2) null,
  ytd_other numeric(18,2) null,
  updated_at timestamptz not null default now()
);
create index if not exists ix_hr_employee_totals_tenant on hr_employee_totals(tenant_id, employee_id);

create table if not exists hr_employee_pay_details (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  employee_id integer not null,
  salary_scale text null,
  pay_frequency text null,
  commission_code text null,
  fica_eobi boolean null,
  state_allowance numeric(18,2) null,
  federal_withholding numeric(18,2) null,
  city_withholding numeric(18,2) null,
  country_filing_status text null,
  amount numeric(18,2) null,
  deductions numeric(18,2) null,
  blank_check_overtime_rate numeric(18,2) null,
  ytd_regular_hours numeric(18,2) null,
  last_agi numeric(18,2) null,
  pregnancy_leaves integer null,
  pay_yn boolean null,
  salary numeric(18,2) null,
  commission_percent numeric(18,2) null,
  federal_income_tax_yn boolean null,
  country_allowance numeric(18,2) null,
  state_withholding numeric(18,2) null,
  federal_filing_status text null,
  city_filing_status text null,
  net_amount numeric(18,2) null,
  pre_tax_amount numeric(18,2) null,
  ytd_fit numeric(18,2) null,
  ytd_overtime_hours numeric(18,2) null,
  last_fica_eobi numeric(18,2) null,
  pay_type text null,
  hourly_rate numeric(18,2) null,
  overtime_rate numeric(18,2) null,
  federal_allowance numeric(18,2) null,
  city_allowance numeric(18,2) null,
  country_withholding_amount numeric(18,2) null,
  state_filing_status text null,
  gender text null,
  blank_check_hourly_rate numeric(18,2) null,
  additions numeric(18,2) null,
  last_gross numeric(18,2) null,
  last_fit numeric(18,2) null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_hr_employee_pay_details_tenant on hr_employee_pay_details(tenant_id, employee_id);

-- =========================
-- CRM + Email tables
-- =========================

create table if not exists phone_notes (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  subject text null,
  body text not null,
  follow_up_at timestamptz null,
  customer_name text null,
  sales_person_name text null,
  created_by integer not null,
  created_at timestamptz not null default now()
);
create index if not exists ix_phone_notes_tenant on phone_notes(tenant_id, created_at desc);

create table if not exists segments (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  created_at timestamptz not null default now()
);
create index if not exists ix_segments_tenant on segments(tenant_id, name);

create table if not exists crm_segment_companies (
  segment_id integer not null,
  company_id integer not null,
  tenant_id integer not null,
  primary key (segment_id, company_id, tenant_id)
);

create table if not exists crm_companies (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  company_name text not null,
  company_details text null,
  company_type text null,
  product text null,
  hs_code text null,
  phone text null,
  cell_phone text null,
  whatsapp text null,
  website text null,
  address text null,
  city text null,
  state text null,
  zip text null,
  country text null,
  ntn text null,
  instagram text null,
  facebook text null,
  twitter text null,
  linkedin text null,
  skype text null,
  source_of_contact text null,
  status text not null default 'Lead',
  saved_updated_on timestamptz null,
  send_email_on_save boolean not null default false,
  created_by integer null,
  created_at timestamptz not null default now()
);
create index if not exists ix_crm_companies_tenant on crm_companies(tenant_id, company_name);

create table if not exists crm_contact_persons (
  id integer generated by default as identity primary key,
  company_id integer not null,
  first_name text null,
  last_name text null,
  designation text null,
  email text null,
  phone text null,
  cell_phone text null,
  whatsapp text null,
  linkedin text null,
  skype text null
);
create index if not exists ix_crm_persons_company on crm_contact_persons(company_id);

create table if not exists crm_categories (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  role_code text not null,
  name text not null
);
create index if not exists ix_crm_categories_tenant_role on crm_categories(tenant_id, role_code);

create table if not exists crm_company_category_map (
  company_id integer not null,
  category_id integer not null,
  primary key (company_id, category_id)
);

create table if not exists crm_appointments (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  company text null,
  notes text null,
  when_at timestamptz not null,
  created_by integer null,
  created_at timestamptz not null default now()
);
create index if not exists ix_crm_appointments_tenant on crm_appointments(tenant_id, when_at);

create table if not exists crm_email_campaigns (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  subject text null,
  scheduled_at timestamptz null,
  created_by integer null,
  created_at timestamptz not null default now()
);
create index if not exists ix_crm_campaigns_tenant on crm_email_campaigns(tenant_id, created_at desc);

create table if not exists crm_accounts (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  created_at timestamptz not null default now()
);
create index if not exists ix_crm_accounts_tenant on crm_accounts(tenant_id);

create table if not exists crm_leads (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  lead_name text not null,
  company text not null,
  email text not null,
  phone text null,
  status text not null default 'New',
  estimated_value numeric(18,2) not null default 0,
  source text null,
  notes text null,
  created_by integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_crm_leads_tenant_status on crm_leads(tenant_id, status);

create table if not exists crm_orders (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  order_number text null,
  order_type text not null,
  party_name text not null,
  contact_person text null,
  email text null,
  address text null,
  items text null,
  subtotal numeric(18,2) not null default 0,
  tax numeric(18,2) not null default 0,
  total_amount numeric(18,2) not null default 0,
  status text not null default 'Draft',
  notes text null,
  lead_id integer null,
  created_by integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  shipped_at timestamptz null
);
create index if not exists ix_crm_orders_tenant_type on crm_orders(tenant_id, order_type);
create index if not exists ix_crm_orders_status on crm_orders(status);

create table if not exists emails (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  user_id integer null,
  folder text not null default 'Inbox',
  from_address text null,
  to_addresses text null,
  cc_addresses text null,
  subject text null,
  body text null,
  attachments_json text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now()
);
create index if not exists ix_emails_tenant_user_folder on emails(tenant_id, user_id, folder, created_at desc);

-- =========================
-- Chat tables
-- =========================

create table if not exists conversations (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  title text not null,
  created_by integer not null,
  created_at timestamptz not null default now()
);

create table if not exists conversation_members (
  id integer generated by default as identity primary key,
  conversation_id integer not null,
  user_id integer not null,
  added_at timestamptz not null default now(),
  unique (conversation_id, user_id)
);

create table if not exists messages (
  id integer generated by default as identity primary key,
  conversation_id integer not null,
  user_id integer not null,
  body text not null,
  created_at timestamptz not null default now()
);
create index if not exists ix_messages_conv on messages(conversation_id, created_at desc);
