-- Safety-domain schema for Supabase (PostgreSQL)
-- Generated from SQL Server introspection: fire/gas/electrical/boiler/structural
-- safety inspections, DSA, consultant engagement, safety audits/RFQ/training/
-- grievances/incidents/documents, and water/waste management.
-- Source tables have no FK constraints, check constraints, triggers, or views
-- (confirmed via sys.foreign_keys / sys.check_constraints / sys.triggers / sys.views).

create table if not exists boiler_safety (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null default now(),
  factory_id integer null,
  location text null,
  inspected_by text null,
  safety_programme text null,
  factory_collaboration text null,
  boiler_design text null,
  boiler_inspection text null,
  inspection_verifies text null,
  rapid_depressurization text null,
  nameplate_visible text null,
  fire_outlets text null,
  low_water_indicator text null,
  maintenance_logbook text null,
  design_manuals text null,
  certified_engineers text null,
  safety_department text null,
  engineers_trained text null,
  advanced_training text null,
  practical_training text null,
  water_source text null,
  water_storage_tank integer null,
  water_softener text null,
  boiler_pressure numeric(10,2) null,
  water_level text null,
  temperature numeric(10,2) null,
  chemical_used text null,
  chemical_type text null,
  dosage_rate numeric(10,2) null,
  feed_method text null,
  p_h numeric(10,2) null,
  alkalinity integer null,
  hardness integer null,
  chlorides integer null,
  silica integer null,
  dissolved_solids integer null,
  blowdown_frequency text null,
  blowdown_method text null,
  steam_pressure numeric(10,2) null,
  steam_temperature numeric(10,2) null,
  steam_traps text null,
  insulation text null,
  condensate_return text null,
  condensate_tank text null,
  condensate_pump text null,
  ventilation text null,
  lighting text null,
  exhaust_fan text null,
  exhaust_duct text null,
  stack_temp_sensor text null,
  safety_valves text null,
  pressure_gauge text null,
  low_water_cutoff text null,
  flame_safeguard text null,
  emergency_shutoff text null,
  fuel_train_shutoff text null,
  interlock_overtemperature text null,
  interlock_low_water text null,
  interlock_flame_failure text null,
  relief_valve_pressure numeric(10,2) null,
  observations text null,
  status text null default 'Open',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create table if not exists consultant_engagement (
  id integer generated by default as identity primary key,
  assessment_date timestamptz not null default now(),
  consultant_name text null,
  project_name text null,
  assessed_by text null,
  legal_registered text null,
  valid_licenses text null,
  international_memberships text null,
  no_false_claims text null,
  independent_verification text null,
  no_conflict_interest text null,
  c_vs_provided text null,
  key_personnel_identified text null,
  responsibilities_defined text null,
  scope_of_work_defined text null,
  deliverables_specified text null,
  timeline_realistic text null,
  payment_terms_clear text null,
  testing_independent text null,
  insurance_coverage text null,
  warranty_provided text null,
  comments text null,
  status text null default 'Under Review',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create table if not exists contact_test (
  id integer generated by default as identity primary key,
  name text not null,
  created_date timestamptz null default now()
);

create table if not exists dsa (
  id integer generated by default as identity primary key,
  assessment_date timestamptz not null default now(),
  factory_id integer null,
  location text null,
  assessed_by text null,
  bulk_drawings text null,
  site_inspection text null,
  visual_checks text null,
  missing_docs text null,
  ndt_testing text null,
  analytical_model text null,
  capacity_verified text null,
  load_paths text null,
  adequacy_checked text null,
  observations text null,
  status text null default 'In Progress',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create table if not exists electrical_safety (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null,
  location text null,
  equipment_type text null,
  equipment_id text null,
  voltage text null,
  wiring_condition text null,
  grounding_status text null,
  circuit_breakers_working text null,
  electrical_panel_condition text null,
  emergency_shutoff_accessible text null,
  labeling_complete text null,
  deficiencies text null,
  corrective_actions text null,
  inspected_by text null,
  status text null default 'Compliant',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists emergency_power (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null default now(),
  factory_id integer null,
  location text null,
  inspected_by text null,
  site_plan text null,
  egress_layout text null,
  floor_plans text null,
  elevations text null,
  roof_plan text null,
  pump_room_fire_resistance text null,
  pump_room_openlined text null,
  pump_selection text null,
  pump_room_ventilation text null,
  drainage_sump text null,
  clearances text null,
  components_listed text null,
  standard_details text null,
  fire_doors text null,
  pipe_sizes text null,
  no_combustibles text null,
  structure_verified text null,
  live_loads text null,
  wind_loads text null,
  seismic_checked text null,
  dimensions_verified text null,
  visual_inspection text null,
  foundation_verified text null,
  structural_calculations text null,
  roof_design text null,
  fire_resistance text null,
  nonstructural_braced text null,
  floor_load_limits text null,
  equipment_foundations text null,
  anchoring text null,
  battery_fire_rooms text null,
  door_hung text null,
  light_working_space text null,
  penetrations_sealed text null,
  single_line_diagram text null,
  backup_power_sized text null,
  automatic_start text null,
  atsups_isolation text null,
  circuit_breakers text null,
  electrical_components_listed text null,
  cables_sized text null,
  earthing_grounding text null,
  surge_protection text null,
  emergency_lighting text null,
  supervisory_alarms text null,
  dedicated_battery_room text null,
  battery_ventilation text null,
  room_door_vents text null,
  battery_temperature text null,
  spill_containment text null,
  battery_racks text null,
  eyewash_station text null,
  smoke_heat_detectors text null,
  emergency_lighting_battery_room text null,
  clear_access text null,
  additional_notes text null,
  status text null default 'Pending Review',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create table if not exists fire_safety (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null,
  location text null,
  equipment_type text null,
  equipment_id text null,
  fire_extinguishers_count integer null,
  fire_extinguishers_working text null,
  smoke_detectors_count integer null,
  smoke_detectors_working text null,
  fire_alarms_working text null,
  emergency_exits_clear text null,
  fire_drill_conducted text null,
  last_drill_date timestamptz null,
  deficiencies text null,
  corrective_actions text null,
  inspected_by text null,
  status text null default 'Compliant',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists gas_safety (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null default now(),
  factory_id integer null,
  location text null,
  inspected_by text null,
  worker_safety text null,
  explosion_controls text null,
  prohibited_storage text null,
  nfpa_standard text null,
  technical_guidance text null,
  safe_storage text null,
  transitional_storage text null,
  transitional_compliance text null,
  room_enclosed text null,
  fire_doors text null,
  verified_compliant text null,
  ongoing_compliance text null,
  building_distance text null,
  exterior_walls text null,
  doors_rating text null,
  building_sole_use text null,
  ventilation_installed text null,
  building_approved text null,
  cylinders_stored_condition text null,
  cylinders_kept_away text null,
  cylinders_upright text null,
  cylinders_secured text null,
  valve_protection text null,
  full_empty_separation text null,
  empty_cylinders_marked text null,
  properly_sized text null,
  no_leaks text null,
  regularly_inspected text null,
  approved_connections text null,
  no_tools_valves text null,
  hydrostatic_testing text null,
  cylinders_checked text null,
  cylinders_moved_trucks text null,
  leaking_tagged text null,
  leaking_moved text null,
  warning_signs_posted text null,
  supplier_notified text null,
  inspections_protocols text null,
  ca_ps_prepared text null,
  reports_documented text null,
  observations text null,
  corrective_actions text null,
  status text null default 'Open',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create table if not exists health_hazards (
  id integer generated by default as identity primary key,
  assessment_date timestamptz not null,
  location text null,
  hazard_type text null,
  chemical_exposure text null,
  chemical_names text null,
  noise_level text null,
  ventilation_adequate text null,
  ppe_available text null,
  ppe_types text null,
  first_aid_available text null,
  wash_stations_accessible text null,
  hazard_severity text null,
  risk_level text null,
  deficiencies text null,
  corrective_actions text null,
  assessed_by text null,
  status text null default 'Under Review',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_audit_corrective_action (
  id integer generated by default as identity primary key,
  audit_item_id integer not null,
  corrective_action_taken text null,
  attachments text null,
  corrective_action_by text null,
  corrective_action_on timestamptz null,
  created_date timestamptz not null default now(),
  resolution_mode text null,
  resolution_amount numeric(18,2) null,
  status text null
);

create table if not exists safety_audit_item (
  id integer generated by default as identity primary key,
  audit_id integer not null,
  head text not null,
  value text null,
  no_issue boolean not null default true,
  issue_details text null,
  attachments text null,
  suggested_action text null,
  informed_to text null,
  created_date timestamptz not null default now(),
  updated_date timestamptz null
);

create table if not exists safety_audit_log (
  log_id integer generated by default as identity primary key,
  proposal_id integer null,
  action text not null,
  actor_id integer null,
  message text null,
  created_at timestamptz not null default now()
);

create table if not exists safety_audit_plan (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  audit_name text not null,
  audit_type text not null,
  audit_company text null,
  audit_date timestamptz null,
  status text not null default 'Planned',
  created_by text null,
  created_date timestamptz not null default now(),
  updated_date timestamptz null
);

create table if not exists safety_audit_reaudit (
  id integer generated by default as identity primary key,
  audit_id integer not null,
  notes text null,
  attachments text null,
  status text not null default 'Closed',
  created_by text null,
  created_date timestamptz not null default now()
);

create table if not exists safety_boiler_safety (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_checklist_headings (
  id integer generated by default as identity primary key,
  tab_id text not null,
  heading_text text not null,
  heading_slug text not null,
  display_order integer null default 0,
  created_at timestamptz null default now(),
  created_by text null,
  unique (tab_id, heading_slug) -- was UQ_SafetyChecklistHeadings_TabHeading
);
create index if not exists ix_safety_checklist_headings_tab_id on safety_checklist_headings(tab_id);

create table if not exists safety_checklist_items (
  id integer generated by default as identity primary key,
  tab_id text not null,
  heading_text text not null,
  heading_slug text not null,
  item_text text not null,
  options text not null,
  display_order integer null default 0,
  created_at timestamptz null default now(),
  created_by text null,
  updated_at timestamptz null,
  is_active boolean null default true
);
create index if not exists ix_safety_checklist_items_tab_id_heading_slug on safety_checklist_items(tab_id, heading_slug);

create table if not exists safety_consultant (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_documents (
  document_id integer generated by default as identity primary key,
  tenant_id integer null,
  file_name text not null,
  file_path text not null,
  mime_type text null,
  size_bytes bigint null,
  extracted_text text null,
  uploaded_by integer null,
  uploaded_at timestamptz not null default now()
);

create table if not exists safety_dsa (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_electrical (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  inspection_date date null,
  location text null,
  inspected_by text null,
  form_data text null,
  status text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_emergency_power (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_fire_safety (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_gas_safety (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_grievances (
  id integer generated by default as identity primary key,
  grievance_date timestamptz not null,
  complainant_name text null,
  complainant_role text null,
  grievance_type text null,
  category text null,
  description text null,
  priority text null,
  assigned_to text null,
  resolution_details text null,
  status text null default 'Pending',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_health_hazards (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  assessment_date date null,
  location text null,
  assessed_by text null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_incidents (
  id integer generated by default as identity primary key,
  incident_date timestamptz not null,
  incident_type text null,
  location text null,
  department text null,
  description text null,
  injury_occurred text null,
  property_damage text null,
  severity text null,
  reported_by text null,
  investigation_status text null,
  corrective_action text null,
  status text null default 'Open',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_proposal_items (
  item_id integer generated by default as identity primary key,
  proposal_id integer not null,
  target_table text not null,
  action text not null,
  payload text not null
);

create table if not exists safety_proposals (
  proposal_id integer generated by default as identity primary key,
  tenant_id integer null,
  title text null,
  description text null,
  status text not null default 'pending',
  document_id integer null,
  submitted_by integer null,
  submitted_at timestamptz not null default now(),
  approved_by integer null,
  approved_at timestamptz null,
  rejected_by integer null,
  rejected_at timestamptz null,
  rejection_reason text null
);

create table if not exists safety_rfq (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  audit_id integer null,
  audit_item_id integer null,
  item_name text not null,
  detail text null,
  qty numeric(18,2) null,
  unit text null,
  needed_by timestamptz null,
  shipping_terms text null,
  payment_terms text null,
  other_terms text null,
  recipients text null,
  status text not null default 'Open',
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null
);

create table if not exists safety_rfq_invoice (
  id integer generated by default as identity primary key,
  quote_id integer not null,
  invoice_number text not null,
  subtotal numeric(18,2) null,
  tax numeric(18,2) null,
  total numeric(18,2) null,
  attachment_url text null,
  status text not null default 'Invoiced',
  created_date timestamptz null default now(),
  updated_date timestamptz null
);

create table if not exists safety_rfq_quote (
  id integer generated by default as identity primary key,
  rfq_id integer not null,
  supplier_name text null,
  supplier_email text null,
  price numeric(18,2) null,
  shipping_cost numeric(18,2) null,
  tax numeric(18,2) null,
  discount numeric(18,2) null,
  total numeric(18,2) null,
  arrival_date timestamptz null,
  shipping_terms text null,
  payment_terms text null,
  other_terms text null,
  status text not null default 'Submitted',
  approved boolean not null default false,
  approved_date timestamptz null,
  po_number text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null
);

create table if not exists safety_safety_training (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_structural (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  inspection_date date null,
  location text null,
  structure_type text null,
  inspected_by text null,
  form_data text null,
  status text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_training_attendee (
  id integer generated by default as identity primary key,
  session_id integer not null,
  employee_id integer null,
  name text null,
  email text null,
  created_date timestamptz null default now()
);

create table if not exists safety_training_session (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  description text null,
  related_to text null,
  training_date timestamptz null,
  conducted_by text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null
);

create table if not exists safety_ungp (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists safety_units (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  created_date timestamptz null default now(),
  unique (tenant_id, name) -- was UQ_SafetyUnits
);

create table if not exists safety_usc_safe (
  id integer generated by default as identity primary key,
  tenant_id integer null,
  form_data text null,
  created_by text null,
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists structural_safety (
  id integer generated by default as identity primary key,
  inspection_date timestamptz not null,
  location text null,
  structure_type text null,
  floor_condition text null,
  wall_condition text null,
  ceiling_condition text null,
  staircase_condition text null,
  railings_secure text null,
  cracks_visible text null,
  water_leakage text null,
  load_bearing_capacity text null,
  deficiencies text null,
  corrective_actions text null,
  inspected_by text null,
  status text null default 'Safe',
  created_date timestamptz null default now(),
  updated_date timestamptz null default now()
);

create table if not exists waste_management (
  id integer generated by default as identity primary key,
  date_of_waste_generation date not null,
  waste_category text not null,
  type_of_waste text not null,
  quantity_of_waste numeric(10,2) not null,
  unit text not null,
  source_of_waste text not null,
  collection_method text not null,
  storage_method text not null,
  storage_duration_days integer not null,
  warehouse_name text not null,
  location text not null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_waste_management_waste_category on waste_management(waste_category);
create index if not exists ix_waste_management_date_of_waste_generation on waste_management(date_of_waste_generation);
create index if not exists ix_waste_management_warehouse_name on waste_management(warehouse_name);

create table if not exists water_buying (
  id integer generated by default as identity primary key,
  supplier_name text not null,
  supplier_contact text not null,
  date_of_purchase date not null,
  quantity_purchased numeric(10,2) not null,
  unit text not null,
  cost_per_unit numeric(10,2) not null,
  total_cost numeric(10,2) not null,
  payment_method text not null,
  invoice_number text not null,
  water_tank text not null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null,
  unique (invoice_number) -- was UQ__water_bu__8081A63A3438E3A0
);
create index if not exists ix_water_buying_date_of_purchase on water_buying(date_of_purchase);
create index if not exists ix_water_buying_water_tank on water_buying(water_tank);

create table if not exists water_discharge_quality (
  id integer generated by default as identity primary key,
  monitoring_frequency text not null,
  sampling_points_locations text not null,
  person_responsible text not null,
  comments_observations text null,
  laboratory_used text null,
  parameters_monitored text not null,
  result_value numeric(10,4) null,
  units text null,
  compliance_standards text null,
  monitoring_equipment text null,
  monitoring_date date not null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_water_discharge_quality_monitoring_date on water_discharge_quality(monitoring_date);
create index if not exists ix_water_discharge_quality_parameters_monitored on water_discharge_quality(parameters_monitored);

create table if not exists water_rain_collection (
  id integer generated by default as identity primary key,
  collection_date date not null,
  collection_location text not null,
  quantity_collected numeric(10,2) not null,
  collection_unit text not null,
  rain_tank text not null,
  water_quality text not null,
  treatment_required text not null,
  treatment_type text null,
  collected_by text not null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_water_rain_collection_collection_date on water_rain_collection(collection_date);

create table if not exists water_recycling (
  id integer generated by default as identity primary key,
  department text not null,
  date_of_recycling date not null,
  recycling_method text not null,
  quantity_recycled numeric(10,2) not null,
  unit text not null,
  water_tank text not null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_water_recycling_date_of_recycling on water_recycling(date_of_recycling);
create index if not exists ix_water_recycling_department on water_recycling(department);

create table if not exists water_usage (
  id integer generated by default as identity primary key,
  department text not null,
  date_of_usage date not null,
  quantity_used numeric(10,2) not null,
  unit text not null,
  purpose_of_usage text not null,
  water_efficient_tech text not null,
  reduction_percentage numeric(5,2) null,
  source_of_water text not null,
  available_qty numeric(10,2) null,
  usage_month date null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_water_usage_date_of_usage on water_usage(date_of_usage);
create index if not exists ix_water_usage_department on water_usage(department);

create table if not exists water_waste (
  id integer generated by default as identity primary key,
  department text not null,
  date_of_waste_generation date not null,
  quantity_of_wastewater numeric(10,2) not null,
  unit text not null,
  type_of_wastewater text not null,
  wastewater_treatment_process text not null,
  percentage_of_pollutant_removal numeric(5,2) null,
  disposal_method text not null,
  quantity_disposed numeric(10,2) not null,
  disposed_unit text not null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  created_by text null,
  updated_by text null
);
create index if not exists ix_water_waste_date_of_waste_generation on water_waste(date_of_waste_generation);
create index if not exists ix_water_waste_department on water_waste(department);

