-- Additional Safety-domain tables not present in the original SQL Server
-- introspection because they were created on-demand (IF NOT EXISTS) and had
-- never actually been instantiated: AI prompt templates and barcode-based
-- attendance tracking. No data to migrate for these; schema only.

create table if not exists safety_ai_prompt_templates (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  category text null,
  content text not null,
  created_by text null,
  created_date timestamptz not null default now(),
  updated_date timestamptz null
);

create table if not exists safety_attendance_barcode (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  user_id integer not null,
  barcode text not null,
  photo_url text null,
  created_date timestamptz not null default now(),
  unique (tenant_id, user_id),
  unique (tenant_id, barcode)
);

create table if not exists safety_attendance_log (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  user_id integer not null,
  direction text not null,
  "timestamp" timestamptz not null default now(),
  source text null,
  device_id text null,
  notes text null
);
create index if not exists ix_safety_attendance_log_tenant_time on safety_attendance_log(tenant_id, "timestamp" desc);
