-- Payroll tax setup (country-neutral).
-- HR defines a tax profile per tenant (one per country / tax year) made of
-- rules; payroll computes withholding from the active, HR-verified profile.
-- No statutory rates are shipped here: tax law differs by country and changes
-- every year, so HR must enter and verify the rules from official sources.

create table if not exists hr_tax_profile (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  country text not null,
  currency text null,
  effective_from date not null,
  effective_to date null,
  is_active boolean not null default true,
  source_reference text null,          -- e.g. link/name of the official tax table used
  notes text null,
  verified_by integer null,            -- users.user_id of the HR person who verified it
  verified_at timestamptz null,        -- cleared whenever the profile or its rules change
  created_by integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_hr_tax_profile_tenant on hr_tax_profile(tenant_id, is_active, effective_from desc);

create table if not exists hr_tax_rule (
  id integer generated by default as identity primary key,
  profile_id integer not null references hr_tax_profile(id) on delete cascade,
  sort_order integer not null default 0,
  name text not null,                  -- e.g. "Income tax", "EOBI", "Social security"
  category text not null default 'income_tax',   -- income_tax | social_security | other
  payer text not null default 'employee',        -- employee (deducted) | employer (company cost)
  method text not null,                -- annual_slabs | percent | fixed
  rate numeric(9,4) null,              -- percent method: % of monthly gross
  base_cap numeric(18,2) null,         -- percent method: max monthly wage the % applies to
  amount_cap numeric(18,2) null,       -- percent method: max monthly amount
  fixed_amount numeric(18,2) null,     -- fixed method: monthly amount
  slabs jsonb null,                    -- annual_slabs: [{"from":0,"to":600000,"fixed":0,"rate":0}, ...]
  created_at timestamptz not null default now()
);
create index if not exists ix_hr_tax_rule_profile on hr_tax_rule(profile_id, sort_order);

-- Every payroll run records that HR confirmed the tax setup for that period.
create table if not exists hr_payroll_tax_confirmation (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  period text not null,                -- YYYY-MM
  profile_id integer null,
  confirmed_by integer not null,
  confirmed_at timestamptz not null default now()
);
create index if not exists ix_hr_payroll_tax_conf_tenant on hr_payroll_tax_confirmation(tenant_id, period);
