-- Face-verified attendance (phase 1) and the HR attendance register (phase 2).
-- Builds on safety_attendance_log (05_safety_extra_schema.sql), which keeps
-- one row per check-in/out for every method (barcode, face, scanner, manual).
-- Safe to re-run.

-- Work sites with a GPS geofence. Check-ins must fall inside one of the
-- tenant's active sites (when require_geofence is on).
create table if not exists attendance_site (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  radius_m integer not null default 150,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_attendance_site_tenant on attendance_site(tenant_id, active);

-- Per-tenant rules. Defaults are deliberately strict.
-- Thresholds were chosen from tests where different people scored up to
-- ~0.57 and the same person ~0.8; tune them on real employees during a pilot.
create table if not exists attendance_settings (
  tenant_id integer primary key,
  match_threshold numeric(4,3) not null default 0.620,    -- face similarity needed to accept (0..1)
  review_threshold numeric(4,3) not null default 0.700,   -- accepted but below this -> flagged for HR review
  liveness_threshold numeric(4,3) not null default 0.500, -- anti-spoof score below this -> flagged; below half of it -> refused
  require_geofence boolean not null default true,
  max_gps_accuracy_m integer not null default 100,        -- worse GPS accuracy is flagged
  min_minutes_between integer not null default 2,         -- duplicate check-ins inside this window are refused
  photo_retention_days integer not null default 90,       -- check-in photos are deleted after this (reviewed/accepted rows)
  updated_at timestamptz not null default now()
);

-- Lets a dedicated kiosk account identify employees by face without full HR access.
insert into permissions(code, description, module_id)
select 'ATTENDANCE_KIOSK', 'Run the attendance kiosk (face check-in for any employee)', null
where not exists (select 1 from permissions where code = 'ATTENDANCE_KIOSK');

-- One active face enrollment per employee. Only the face embedding (a list of
-- numbers) is used for matching; the photo is kept so HR can see who was
-- enrolled. Consent is required and recorded.
create table if not exists attendance_face_enrollment (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  user_id integer not null,
  embedding real[] not null,
  photo text null,                     -- small JPEG data URL for HR reference
  quality numeric(4,3) null,
  consent_at timestamptz not null,
  consent_by integer not null,         -- HR user who recorded the employee's consent
  enrolled_by integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists ux_attendance_face_enrollment_active
  on attendance_face_enrollment(tenant_id, user_id) where active;

-- Server-issued liveness challenges. Each can be used once, briefly, by the
-- user/device it was issued for, so recorded videos/photos can't be replayed.
create table if not exists attendance_challenge (
  id uuid primary key,
  tenant_id integer not null,
  issued_to integer not null,          -- user who requested it (employee, or kiosk operator)
  mode text not null,                  -- self | kiosk
  action text not null,                -- turn_left | turn_right | blink
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz null
);
create index if not exists ix_attendance_challenge_expiry on attendance_challenge(expires_at);

-- Evidence and review fields on every attendance log row.
alter table safety_attendance_log add column if not exists method text null;            -- barcode | face | scanner | manual
alter table safety_attendance_log add column if not exists match_score numeric(5,4) null;
alter table safety_attendance_log add column if not exists liveness_score numeric(5,4) null;
alter table safety_attendance_log add column if not exists latitude double precision null;
alter table safety_attendance_log add column if not exists longitude double precision null;
alter table safety_attendance_log add column if not exists gps_accuracy_m double precision null;
alter table safety_attendance_log add column if not exists site_id integer null;
alter table safety_attendance_log add column if not exists distance_m double precision null;
alter table safety_attendance_log add column if not exists ip text null;
alter table safety_attendance_log add column if not exists user_agent text null;
alter table safety_attendance_log add column if not exists photo text null;              -- check-in snapshot (JPEG data URL)
alter table safety_attendance_log add column if not exists flags text[] null;            -- reasons a check-in needs review
alter table safety_attendance_log add column if not exists review_status text null;      -- ok | flagged | approved | rejected
alter table safety_attendance_log add column if not exists reviewed_by integer null;
alter table safety_attendance_log add column if not exists reviewed_at timestamptz null;
alter table safety_attendance_log add column if not exists review_note text null;
alter table safety_attendance_log add column if not exists recorded_by integer null;     -- who submitted it (kiosk operator / self)

create index if not exists ix_safety_attendance_log_review on safety_attendance_log(tenant_id, review_status);
create index if not exists ix_safety_attendance_log_user_time on safety_attendance_log(tenant_id, user_id, "timestamp" desc);

-- Every refused attempt is kept too, so HR can see attempted false attendance.
create table if not exists attendance_rejected_attempt (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  claimed_user_id integer null,        -- for self check-in: the signed-in user
  matched_user_id integer null,        -- best face match, if any
  recorded_by integer not null,
  mode text not null,
  reasons text[] not null,
  match_score numeric(5,4) null,
  liveness_score numeric(5,4) null,
  latitude double precision null,
  longitude double precision null,
  gps_accuracy_m double precision null,
  ip text null,
  user_agent text null,
  photo text null,
  created_at timestamptz not null default now()
);
create index if not exists ix_attendance_rejected_attempt_tenant on attendance_rejected_attempt(tenant_id, created_at desc);
