-- Tasks per company, payroll run guard, and salary advances. Safe to re-run.

-- Task planner (previously a JSON file shared by every company and wiped on
-- each deploy). ids keep the "t_xxxx" format the planner pages use.
create table if not exists planner_task (
  id text primary key,
  tenant_id integer not null,
  title text not null,
  task_date date not null,
  assignee_id integer null,
  start_hour integer not null default 0,
  end_hour integer not null default 1,
  priority text not null default 'High',
  note text null,
  created_by integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create index if not exists ix_planner_task_tenant_date on planner_task(tenant_id, task_date);

-- One payroll run per company per month: generating a month twice would
-- create duplicate payables (and deduct advances twice).
create table if not exists hr_payroll_run (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  period text not null,                 -- YYYY-MM
  generated_by integer not null,
  generated_at timestamptz not null default now(),
  employee_count integer not null default 0,
  total_net numeric(18,2) not null default 0,
  total_advance_deductions numeric(18,2) not null default 0,
  unique (tenant_id, period)
);

-- Salary advances: requested by the employee or HR, approved by HR (which
-- creates a payable so Accounts pays it out), then recovered from payroll in
-- monthly installments starting at start_period.
create table if not exists hr_salary_advance (
  id integer generated by default as identity primary key,
  tenant_id integer not null,
  employee_id integer not null,         -- company_users.company_user_id (payroll employee id)
  amount numeric(18,2) not null check (amount > 0),
  installments integer not null default 1 check (installments between 1 and 24),
  monthly_deduction numeric(18,2) not null,
  start_period text not null,           -- YYYY-MM of the first deduction
  reason text null,
  status text not null default 'Pending',   -- Pending | Approved | Rejected | Repaid
  repaid_amount numeric(18,2) not null default 0,
  requested_by integer not null,
  requested_at timestamptz not null default now(),
  decided_by integer null,
  decided_at timestamptz null,
  decision_note text null,
  ap_invoice_order_id text null,         -- payable created on approval
  updated_at timestamptz null
);
create index if not exists ix_hr_salary_advance_tenant on hr_salary_advance(tenant_id, status);

create table if not exists hr_salary_advance_deduction (
  id integer generated by default as identity primary key,
  advance_id integer not null references hr_salary_advance(id) on delete cascade,
  tenant_id integer not null,
  period text not null,
  amount numeric(18,2) not null,
  payroll_run_id integer null,
  created_at timestamptz not null default now(),
  unique (advance_id, period)
);
