[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node src/setup-db.js && node src/web-server.js"
