[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "sh -c 'node src/setup-db.js > /tmp/setup-db.log 2>&1 & node src/web-server.js'"
